"""empty message

Revision ID: 52fde6fe89c6
Revises: ea16ba360e5f
Create Date: 2021-07-24 17:10:26.768654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fde6fe89c6'
down_revision = 'ea16ba360e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'provider', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'user_id')
    # ### end Alembic commands ###
