"""empty message

Revision ID: ff270a8cf564
Revises: 1dbce95fbf14
Create Date: 2021-07-17 15:35:36.844599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff270a8cf564'
down_revision = '1dbce95fbf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
